const itemDatabase = [
    {"id": "minecraft:acacia_door", "itemId": 589, "icon": "", "displayName": "Acacia Door", "shortName": "AcaciaDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:acacia_door", "itemId": 196, "icon": "", "displayName": "Acacia Door", "shortName": "AcaciaDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:acacia_leaves", "itemId": 161, "icon": "", "displayName": "Acacia Leaves", "shortName": "AcaciaLeaves", "categories": ["leaves"] },
{"id": "minecraft:acacia_log", "itemId": 162, "icon": "", "displayName": "Acacia Log", "shortName": "AcaciaLog", "categories": ["log"] },
{"id": "minecraft:acacia_planks", "itemId": -742, "icon": "", "displayName": "Acacia Planks", "shortName": "AcaciaPlanks", "categories": ["plank"] },
{"id": "minecraft:acacia_sapling", "itemId": -828, "icon": "", "displayName": "Acacia Sapling", "shortName": "AcaciaSapling", "categories": ["saplings"] },
{"id": "minecraft:allium", "itemId": -831, "icon": "", "displayName": "Allium", "shortName": "Allium", "categories": ["flower"] },
{"id": "minecraft:andesite", "itemId": -594, "icon": "", "displayName": "Andesite", "shortName": "Andesite", "categories": ["stone"] },
{"id": "minecraft:apple", "itemId": 278, "icon": "", "displayName": "Apple", "shortName": "Apple", "categories": ["food"] },
{"id": "minecraft:azalea_leaves", "itemId": -324, "icon": "", "displayName": "Azalea Leaves", "shortName": "AzaleaLeaves", "categories": ["leaves"] },
{"id": "minecraft:azalea_leaves_flowered", "itemId": -325, "icon": "", "displayName": "Azalea Leaves Flowered", "shortName": "AzaleaLeavesFlowered", "categories": ["leaves"] },
{"id": "minecraft:azure_bluet", "itemId": -832, "icon": "", "displayName": "Azure Bluet", "shortName": "AzureBluet", "categories": ["flower"] },
{"id": "minecraft:baked_potato", "itemId": 303, "icon": "", "displayName": "Baked Potato", "shortName": "BakedPotato", "categories": ["food", "cookedFood"] },
{"id": "minecraft:bamboo_door", "itemId": -517, "icon": "", "displayName": "Bamboo Door", "shortName": "BambooDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:bamboo_planks", "itemId": -510, "icon": "", "displayName": "Bamboo Planks", "shortName": "BambooPlanks", "categories": ["plank"] },
{"id": "minecraft:bamboo_sapling", "itemId": -164, "icon": "", "displayName": "Bamboo Sapling", "shortName": "BambooSapling", "categories": ["saplings"] },
{"id": "minecraft:barrel", "itemId": -203, "icon": "", "displayName": "Barrel", "shortName": "Barrel", "categories": ["storage"] },
{"id": "minecraft:basalt", "itemId": -234, "icon": "", "displayName": "Basalt", "shortName": "Basalt", "categories": ["stone"] },
{"id": "minecraft:bed", "itemId": 444, "icon": "", "displayName": "Bed", "shortName": "Bed", "categories": ["beds"] },
{"id": "minecraft:beef", "itemId": 295, "icon": "", "displayName": "Beef", "shortName": "Beef", "categories": ["food"] },
{"id": "minecraft:beetroot", "itemId": 307, "icon": "", "displayName": "Beetroot", "shortName": "Beetroot", "categories": ["food"] },
{"id": "minecraft:beetroot_soup", "itemId": 308, "icon": "", "displayName": "Beetroot Soup", "shortName": "BeetrootSoup", "categories": ["food"] },
{"id": "minecraft:birch_door", "itemId": 587, "icon": "", "displayName": "Birch Door", "shortName": "BirchDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:birch_door", "itemId": 194, "icon": "", "displayName": "Birch Door", "shortName": "BirchDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:birch_leaves", "itemId": -801, "icon": "", "displayName": "Birch Leaves", "shortName": "BirchLeaves", "categories": ["leaves"] },
{"id": "minecraft:birch_log", "itemId": -570, "icon": "", "displayName": "Birch Log", "shortName": "BirchLog", "categories": ["log"] },
{"id": "minecraft:birch_planks", "itemId": -740, "icon": "", "displayName": "Birch Planks", "shortName": "BirchPlanks", "categories": ["plank"] },
{"id": "minecraft:birch_sapling", "itemId": -826, "icon": "", "displayName": "Birch Sapling", "shortName": "BirchSapling", "categories": ["saplings"] },
{"id": "minecraft:black_carpet", "itemId": -611, "icon": "", "displayName": "Black Carpet", "shortName": "BlackCarpet", "categories": ["carpet"] },
{"id": "minecraft:black_wool", "itemId": -554, "icon": "", "displayName": "Black Wool", "shortName": "BlackWool", "categories": ["wool"] },
{"id": "minecraft:blackstone", "itemId": -273, "icon": "", "displayName": "Blackstone", "shortName": "Blackstone", "categories": ["stone"] },
{"id": "minecraft:blue_carpet", "itemId": -607, "icon": "", "displayName": "Blue Carpet", "shortName": "BlueCarpet", "categories": ["carpet"] },
{"id": "minecraft:blue_orchid", "itemId": -830, "icon": "", "displayName": "Blue Orchid", "shortName": "BlueOrchid", "categories": ["flower"] },
{"id": "minecraft:blue_wool", "itemId": -563, "icon": "", "displayName": "Blue Wool", "shortName": "BlueWool", "categories": ["wool"] },
{"id": "minecraft:bread", "itemId": 283, "icon": "", "displayName": "Bread", "shortName": "Bread", "categories": ["food"] },
{"id": "minecraft:brown_carpet", "itemId": -608, "icon": "", "displayName": "Brown Carpet", "shortName": "BrownCarpet", "categories": ["carpet"] },
{"id": "minecraft:brown_wool", "itemId": -555, "icon": "", "displayName": "Brown Wool", "shortName": "BrownWool", "categories": ["wool"] },
{"id": "minecraft:carrot", "itemId": 301, "icon": "", "displayName": "Carrot", "shortName": "Carrot", "categories": ["food"] },
{"id": "minecraft:chainmail_boots", "itemId": 367, "icon": "", "displayName": "Chainmail Boots", "shortName": "ChainmailBoots", "categories": ["chainArmor", "armor"] },
{"id": "minecraft:chainmail_chestplate", "itemId": 365, "icon": "", "displayName": "Chainmail Chestplate", "shortName": "ChainmailChestplate", "categories": ["chainArmor", "armor"] },
{"id": "minecraft:chainmail_helmet", "itemId": 364, "icon": "", "displayName": "Chainmail Helmet", "shortName": "ChainmailHelmet", "categories": ["chainArmor", "armor"] },
{"id": "minecraft:chainmail_leggings", "itemId": 366, "icon": "", "displayName": "Chainmail Leggings", "shortName": "ChainmailLeggings", "categories": ["chainArmor", "armor"] },
{"id": "minecraft:cherry_door", "itemId": -531, "icon": "", "displayName": "Cherry Door", "shortName": "CherryDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:cherry_leaves", "itemId": -548, "icon": "", "displayName": "Cherry Leaves", "shortName": "CherryLeaves", "categories": ["leaves"] },
{"id": "minecraft:cherry_log", "itemId": -536, "icon": "", "displayName": "Cherry Log", "shortName": "CherryLog", "categories": ["log"] },
{"id": "minecraft:cherry_planks", "itemId": -537, "icon": "", "displayName": "Cherry Planks", "shortName": "CherryPlanks", "categories": ["plank"] },
{"id": "minecraft:cherry_sapling", "itemId": -547, "icon": "", "displayName": "Cherry Sapling", "shortName": "CherrySapling", "categories": ["saplings"] },
{"id": "minecraft:chest", "itemId": 54, "icon": "", "displayName": "Chest", "shortName": "Chest", "categories": ["storage"] },
{"id": "minecraft:chicken", "itemId": 297, "icon": "", "displayName": "Chicken", "shortName": "Chicken", "categories": ["food"] },
{"id": "minecraft:chorus_fruit", "itemId": 591, "icon": "", "displayName": "Chorus Fruit", "shortName": "ChorusFruit", "categories": ["food"] },
{"id": "minecraft:coal_ore", "itemId": 16, "icon": "", "displayName": "Coal Ore", "shortName": "CoalOre", "categories": ["ore"] },
{"id": "minecraft:cobblestone", "itemId": 4, "icon": "", "displayName": "Cobblestone", "shortName": "Cobblestone", "categories": ["stone"] },
{"id": "minecraft:cod", "itemId": 286, "icon": "", "displayName": "Cod", "shortName": "Cod", "categories": ["food"] },
{"id": "minecraft:cooked_beef", "itemId": 296, "icon": "", "displayName": "Cooked Beef", "shortName": "CookedBeef", "categories": ["food", "cookedFood"] },
{"id": "minecraft:cooked_chicken", "itemId": 298, "icon": "", "displayName": "Cooked Chicken", "shortName": "CookedChicken", "categories": ["food", "cookedFood"] },
{"id": "minecraft:cooked_cod", "itemId": 290, "icon": "", "displayName": "Cooked Cod", "shortName": "CookedCod", "categories": ["food", "cookedFood"] },
{"id": "minecraft:cooked_mutton", "itemId": 584, "icon": "", "displayName": "Cooked Mutton", "shortName": "CookedMutton", "categories": ["food", "cookedFood"] },
{"id": "minecraft:cooked_porkchop", "itemId": 285, "icon": "", "displayName": "Cooked Porkchop", "shortName": "CookedPorkchop", "categories": ["food", "cookedFood"] },
{"id": "minecraft:cooked_rabbit", "itemId": 311, "icon": "", "displayName": "Cooked Rabbit", "shortName": "CookedRabbit", "categories": ["food", "cookedFood"] },
{"id": "minecraft:cooked_salmon", "itemId": 291, "icon": "", "displayName": "Cooked Salmon", "shortName": "CookedSalmon", "categories": ["food", "cookedFood"] },
{"id": "minecraft:cookie", "itemId": 293, "icon": "", "displayName": "Cookie", "shortName": "Cookie", "categories": ["food"] },
{"id": "minecraft:copper_door", "itemId": -784, "icon": "", "displayName": "Copper Door", "shortName": "CopperDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:copper_ingot", "itemId": 538, "icon": "", "displayName": "Copper Ingot", "shortName": "CopperIngot", "categories": ["metalIngots"] },
{"id": "minecraft:copper_ore", "itemId": -311, "icon": "", "displayName": "Copper Ore", "shortName": "CopperOre", "categories": ["ore"] },
{"id": "minecraft:cornflower", "itemId": -838, "icon": "", "displayName": "Cornflower", "shortName": "Cornflower", "categories": ["flower"] },
{"id": "minecraft:crimson_door", "itemId": 653, "icon": "", "displayName": "Crimson Door", "shortName": "CrimsonDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:crimson_planks", "itemId": -242, "icon": "", "displayName": "Crimson Planks", "shortName": "CrimsonPlanks", "categories": ["plank"] },
{"id": "minecraft:cyan_carpet", "itemId": -605, "icon": "", "displayName": "Cyan Carpet", "shortName": "CyanCarpet", "categories": ["carpet"] },
{"id": "minecraft:cyan_wool", "itemId": -561, "icon": "", "displayName": "Cyan Wool", "shortName": "CyanWool", "categories": ["wool"] },
{"id": "minecraft:dandelion", "itemId": 37, "icon": "", "displayName": "Dandelion", "shortName": "Dandelion", "categories": ["flower"] },
{"id": "minecraft:dark_oak_door", "itemId": 590, "icon": "", "displayName": "Dark Oak Door", "shortName": "DarkOakDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:dark_oak_door", "itemId": 197, "icon": "", "displayName": "Dark Oak Door", "shortName": "DarkOakDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:dark_oak_leaves", "itemId": -803, "icon": "", "displayName": "Dark Oak Leaves", "shortName": "DarkOakLeaves", "categories": ["leaves"] },
{"id": "minecraft:dark_oak_log", "itemId": -572, "icon": "", "displayName": "Dark Oak Log", "shortName": "DarkOakLog", "categories": ["log"] },
{"id": "minecraft:dark_oak_planks", "itemId": -743, "icon": "", "displayName": "Dark Oak Planks", "shortName": "DarkOakPlanks", "categories": ["plank"] },
{"id": "minecraft:dark_oak_sapling", "itemId": -829, "icon": "", "displayName": "Dark Oak Sapling", "shortName": "DarkOakSapling", "categories": ["saplings"] },
{"id": "minecraft:deadbush", "itemId": 32, "icon": "", "displayName": "Deadbush", "shortName": "Deadbush", "categories": ["flower"] },
{"id": "minecraft:deepslate", "itemId": -378, "icon": "", "displayName": "Deepslate", "shortName": "Deepslate", "categories": ["stone"] },
{"id": "minecraft:deepslate_coal_ore", "itemId": -406, "icon": "", "displayName": "Deepslate Coal Ore", "shortName": "DeepslateCoalOre", "categories": ["ore"] },
{"id": "minecraft:deepslate_copper_ore", "itemId": -408, "icon": "", "displayName": "Deepslate Copper Ore", "shortName": "DeepslateCopperOre", "categories": ["ore"] },
{"id": "minecraft:deepslate_diamond_ore", "itemId": -405, "icon": "", "displayName": "Deepslate Diamond Ore", "shortName": "DeepslateDiamondOre", "categories": ["ore"] },
{"id": "minecraft:deepslate_emerald_ore", "itemId": -407, "icon": "", "displayName": "Deepslate Emerald Ore", "shortName": "DeepslateEmeraldOre", "categories": ["ore"] },
{"id": "minecraft:deepslate_gold_ore", "itemId": -402, "icon": "", "displayName": "Deepslate Gold Ore", "shortName": "DeepslateGoldOre", "categories": ["ore"] },
{"id": "minecraft:deepslate_iron_ore", "itemId": -401, "icon": "", "displayName": "Deepslate Iron Ore", "shortName": "DeepslateIronOre", "categories": ["ore"] },
{"id": "minecraft:deepslate_lapis_ore", "itemId": -400, "icon": "", "displayName": "Deepslate Lapis Ore", "shortName": "DeepslateLapisOre", "categories": ["ore"] },
{"id": "minecraft:deepslate_redstone_ore", "itemId": -403, "icon": "", "displayName": "Deepslate Redstone Ore", "shortName": "DeepslateRedstoneOre", "categories": ["ore"] },
{"id": "minecraft:diamond_axe", "itemId": 343, "icon": "", "displayName": "Diamond Axe", "shortName": "DiamondAxe", "categories": ["diamondTools", "tools"] },
{"id": "minecraft:diamond_boots", "itemId": 375, "icon": "", "displayName": "Diamond Boots", "shortName": "DiamondBoots", "categories": ["diamondArmor", "armor"] },
{"id": "minecraft:diamond_chestplate", "itemId": 373, "icon": "", "displayName": "Diamond Chestplate", "shortName": "DiamondChestplate", "categories": ["diamondArmor", "armor"] },
{"id": "minecraft:diamond_helmet", "itemId": 372, "icon": "", "displayName": "Diamond Helmet", "shortName": "DiamondHelmet", "categories": ["diamondArmor", "armor"] },
{"id": "minecraft:diamond_hoe", "itemId": 357, "icon": "", "displayName": "Diamond Hoe", "shortName": "DiamondHoe", "categories": ["diamondTools", "tools"] },
{"id": "minecraft:diamond_leggings", "itemId": 374, "icon": "", "displayName": "Diamond Leggings", "shortName": "DiamondLeggings", "categories": ["diamondArmor", "armor"] },
{"id": "minecraft:diamond_ore", "itemId": 56, "icon": "", "displayName": "Diamond Ore", "shortName": "DiamondOre", "categories": ["ore"] },
{"id": "minecraft:diamond_pickaxe", "itemId": 342, "icon": "", "displayName": "Diamond Pickaxe", "shortName": "DiamondPickaxe", "categories": ["diamondTools", "tools"] },
{"id": "minecraft:diamond_shovel", "itemId": 341, "icon": "", "displayName": "Diamond Shovel", "shortName": "DiamondShovel", "categories": ["diamondTools", "tools"] },
{"id": "minecraft:diamond_sword", "itemId": 340, "icon": "", "displayName": "Diamond Sword", "shortName": "DiamondSword", "categories": ["diamondTools", "tools"] },
{"id": "minecraft:diorite", "itemId": -592, "icon": "", "displayName": "Diorite", "shortName": "Diorite", "categories": ["stone"] },
{"id": "minecraft:dirt", "itemId": 3, "icon": "", "displayName": "Dirt", "shortName": "Dirt", "categories": ["dirt"] },
{"id": "minecraft:dried_kelp", "itemId": 292, "icon": "", "displayName": "Dried Kelp", "shortName": "DriedKelp", "categories": ["flower"] },
{"id": "minecraft:emerald_ore", "itemId": 129, "icon": "", "displayName": "Emerald Ore", "shortName": "EmeraldOre", "categories": ["ore"] },
{"id": "minecraft:enchanted_golden_apple", "itemId": 281, "icon": "", "displayName": "Enchanted Golden Apple", "shortName": "EnchantedGoldenApple", "categories": ["food"] },
{"id": "minecraft:end_stone", "itemId": 121, "icon": "", "displayName": "End Stone", "shortName": "EndStone", "categories": ["stone"] },
{"id": "minecraft:exposed_copper_door", "itemId": -785, "icon": "", "displayName": "Exposed Copper Door", "shortName": "ExposedCopperDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:fermented_spider_eye", "itemId": 455, "icon": "", "displayName": "Fermented Spider Eye", "shortName": "FermentedSpiderEye", "categories": ["food"] },
{"id": "minecraft:glow_berries", "itemId": 796, "icon": "", "displayName": "Glow Berries", "shortName": "GlowBerries", "categories": ["food"] },
{"id": "minecraft:gold_ingot", "itemId": 330, "icon": "", "displayName": "Gold Ingot", "shortName": "GoldIngot", "categories": ["metalIngots"] },
{"id": "minecraft:gold_ore", "itemId": 14, "icon": "", "displayName": "Gold Ore", "shortName": "GoldOre", "categories": ["ore"] },
{"id": "minecraft:golden_apple", "itemId": 280, "icon": "", "displayName": "Golden Apple", "shortName": "GoldenApple", "categories": ["food"] },
{"id": "minecraft:golden_axe", "itemId": 350, "icon": "", "displayName": "Golden Axe", "shortName": "GoldenAxe", "categories": ["goldenTools", "tools"] },
{"id": "minecraft:golden_boots", "itemId": 379, "icon": "", "displayName": "Golden Boots", "shortName": "GoldenBoots", "categories": ["goldenArmor", "armor"] },
{"id": "minecraft:golden_carrot", "itemId": 305, "icon": "", "displayName": "Golden Carrot", "shortName": "GoldenCarrot", "categories": ["food"] },
{"id": "minecraft:golden_chestplate", "itemId": 377, "icon": "", "displayName": "Golden Chestplate", "shortName": "GoldenChestplate", "categories": ["goldenArmor", "armor"] },
{"id": "minecraft:golden_helmet", "itemId": 376, "icon": "", "displayName": "Golden Helmet", "shortName": "GoldenHelmet", "categories": ["goldenArmor", "armor"] },
{"id": "minecraft:golden_hoe", "itemId": 358, "icon": "", "displayName": "Golden Hoe", "shortName": "GoldenHoe", "categories": ["goldenTools", "tools"] },
{"id": "minecraft:golden_leggings", "itemId": 378, "icon": "", "displayName": "Golden Leggings", "shortName": "GoldenLeggings", "categories": ["goldenArmor", "armor"] },
{"id": "minecraft:golden_pickaxe", "itemId": 349, "icon": "", "displayName": "Golden Pickaxe", "shortName": "GoldenPickaxe", "categories": ["goldenTools", "tools"] },
{"id": "minecraft:golden_shovel", "itemId": 348, "icon": "", "displayName": "Golden Shovel", "shortName": "GoldenShovel", "categories": ["goldenTools", "tools"] },
{"id": "minecraft:golden_sword", "itemId": 347, "icon": "", "displayName": "Golden Sword", "shortName": "GoldenSword", "categories": ["goldenTools", "tools"] },
{"id": "minecraft:granite", "itemId": -590, "icon": "", "displayName": "Granite", "shortName": "Granite", "categories": ["stone"] },
{"id": "minecraft:grass_block", "itemId": 2, "icon": "", "displayName": "Grass Block", "shortName": "GrassBlock", "categories": ["dirt"] },
{"id": "minecraft:gray_carpet", "itemId": -603, "icon": "", "displayName": "Gray Carpet", "shortName": "GrayCarpet", "categories": ["carpet"] },
{"id": "minecraft:gray_wool", "itemId": -553, "icon": "", "displayName": "Gray Wool", "shortName": "GrayWool", "categories": ["wool"] },
{"id": "minecraft:green_carpet", "itemId": -609, "icon": "", "displayName": "Green Carpet", "shortName": "GreenCarpet", "categories": ["carpet"] },
{"id": "minecraft:green_wool", "itemId": -560, "icon": "", "displayName": "Green Wool", "shortName": "GreenWool", "categories": ["wool"] },
{"id": "minecraft:honey_bottle", "itemId": 627, "icon": "", "displayName": "Honey Bottle", "shortName": "HoneyBottle", "categories": ["food"] },
{"id": "minecraft:iron_axe", "itemId": 322, "icon": "", "displayName": "Iron Axe", "shortName": "IronAxe", "categories": ["ironTools", "tools"] },
{"id": "minecraft:iron_boots", "itemId": 371, "icon": "", "displayName": "Iron Boots", "shortName": "IronBoots", "categories": ["ironArmor", "armor"] },
{"id": "minecraft:iron_chestplate", "itemId": 369, "icon": "", "displayName": "Iron Chestplate", "shortName": "IronChestplate", "categories": ["ironArmor", "armor"] },
{"id": "minecraft:iron_door", "itemId": 397, "icon": "", "displayName": "Iron Door", "shortName": "IronDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:iron_helmet", "itemId": 368, "icon": "", "displayName": "Iron Helmet", "shortName": "IronHelmet", "categories": ["ironArmor", "armor"] },
{"id": "minecraft:iron_hoe", "itemId": 356, "icon": "", "displayName": "Iron Hoe", "shortName": "IronHoe", "categories": ["ironTools", "tools"] },
{"id": "minecraft:iron_ingot", "itemId": 329, "icon": "", "displayName": "Iron Ingot", "shortName": "IronIngot", "categories": ["metalIngots"] },
{"id": "minecraft:iron_leggings", "itemId": 370, "icon": "", "displayName": "Iron Leggings", "shortName": "IronLeggings", "categories": ["ironArmor", "armor"] },
{"id": "minecraft:iron_ore", "itemId": 15, "icon": "", "displayName": "Iron Ore", "shortName": "IronOre", "categories": ["ore"] },
{"id": "minecraft:iron_pickaxe", "itemId": 321, "icon": "", "displayName": "Iron Pickaxe", "shortName": "IronPickaxe", "categories": ["ironTools", "tools"] },
{"id": "minecraft:iron_shovel", "itemId": 320, "icon": "", "displayName": "Iron Shovel", "shortName": "IronShovel", "categories": ["ironTools", "tools"] },
{"id": "minecraft:iron_sword", "itemId": 331, "icon": "", "displayName": "Iron Sword", "shortName": "IronSword", "categories": ["ironTools", "tools"] },
{"id": "minecraft:jungle_door", "itemId": 588, "icon": "", "displayName": "Jungle Door", "shortName": "JungleDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:jungle_door", "itemId": 195, "icon": "", "displayName": "Jungle Door", "shortName": "JungleDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:jungle_leaves", "itemId": -802, "icon": "", "displayName": "Jungle Leaves", "shortName": "JungleLeaves", "categories": ["leaves"] },
{"id": "minecraft:jungle_log", "itemId": -571, "icon": "", "displayName": "Jungle Log", "shortName": "JungleLog", "categories": ["log"] },
{"id": "minecraft:jungle_planks", "itemId": -741, "icon": "", "displayName": "Jungle Planks", "shortName": "JunglePlanks", "categories": ["plank"] },
{"id": "minecraft:jungle_sapling", "itemId": -827, "icon": "", "displayName": "Jungle Sapling", "shortName": "JungleSapling", "categories": ["saplings"] },
{"id": "minecraft:lapis_ore", "itemId": 21, "icon": "", "displayName": "Lapis Ore", "shortName": "LapisOre", "categories": ["ore"] },
{"id": "minecraft:leather_boots", "itemId": 363, "icon": "", "displayName": "Leather Boots", "shortName": "LeatherBoots", "categories": ["letherArmor", "armor"] },
{"id": "minecraft:leather_chestplate", "itemId": 361, "icon": "", "displayName": "Leather Chestplate", "shortName": "LeatherChestplate", "categories": ["letherArmor", "armor"] },
{"id": "minecraft:leather_helmet", "itemId": 360, "icon": "", "displayName": "Leather Helmet", "shortName": "LeatherHelmet", "categories": ["letherArmor", "armor"] },
{"id": "minecraft:leather_leggings", "itemId": 362, "icon": "", "displayName": "Leather Leggings", "shortName": "LeatherLeggings", "categories": ["letherArmor", "armor"] },
{"id": "minecraft:light_blue_carpet", "itemId": -599, "icon": "", "displayName": "Light Blue Carpet", "shortName": "LightBlueCarpet", "categories": ["carpet"] },
{"id": "minecraft:light_blue_wool", "itemId": -562, "icon": "", "displayName": "Light Blue Wool", "shortName": "LightBlueWool", "categories": ["wool"] },
{"id": "minecraft:light_gray_carpet", "itemId": -604, "icon": "", "displayName": "Light Gray Carpet", "shortName": "LightGrayCarpet", "categories": ["carpet"] },
{"id": "minecraft:light_gray_wool", "itemId": -552, "icon": "", "displayName": "Light Gray Wool", "shortName": "LightGrayWool", "categories": ["wool"] },
{"id": "minecraft:lilac", "itemId": -863, "icon": "", "displayName": "Lilac", "shortName": "Lilac", "categories": ["flower"] },
{"id": "minecraft:lily_of_the_valley", "itemId": -839, "icon": "", "displayName": "Lily Of The Valley", "shortName": "LilyOfTheValley", "categories": ["flower"] },
{"id": "minecraft:lime_carpet", "itemId": -601, "icon": "", "displayName": "Lime Carpet", "shortName": "LimeCarpet", "categories": ["carpet"] },
{"id": "minecraft:lime_wool", "itemId": -559, "icon": "", "displayName": "Lime Wool", "shortName": "LimeWool", "categories": ["wool"] },
{"id": "minecraft:lit_deepslate_redstone_ore", "itemId": -404, "icon": "", "displayName": "Lit Deepslate Redstone Ore", "shortName": "LitDeepslateRedstoneOre", "categories": ["ore"] },
{"id": "minecraft:lit_redstone_ore", "itemId": 74, "icon": "", "displayName": "Lit Redstone Ore", "shortName": "LitRedstoneOre", "categories": ["ore"] },
{"id": "minecraft:magenta_carpet", "itemId": -598, "icon": "", "displayName": "Magenta Carpet", "shortName": "MagentaCarpet", "categories": ["carpet"] },
{"id": "minecraft:magenta_wool", "itemId": -565, "icon": "", "displayName": "Magenta Wool", "shortName": "MagentaWool", "categories": ["wool"] },
{"id": "minecraft:mangrove_door", "itemId": 670, "icon": "", "displayName": "Mangrove Door", "shortName": "MangroveDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:mangrove_door", "itemId": -493, "icon": "", "displayName": "Mangrove Door", "shortName": "MangroveDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:mangrove_leaves", "itemId": -472, "icon": "", "displayName": "Mangrove Leaves", "shortName": "MangroveLeaves", "categories": ["leaves"] },
{"id": "minecraft:mangrove_log", "itemId": -484, "icon": "", "displayName": "Mangrove Log", "shortName": "MangroveLog", "categories": ["log"] },
{"id": "minecraft:mangrove_planks", "itemId": -486, "icon": "", "displayName": "Mangrove Planks", "shortName": "MangrovePlanks", "categories": ["plank"] },
{"id": "minecraft:melon_slice", "itemId": 294, "icon": "", "displayName": "Melon Slice", "shortName": "MelonSlice", "categories": ["food"] },
{"id": "minecraft:moss_carpet", "itemId": -335, "icon": "", "displayName": "Moss Carpet", "shortName": "MossCarpet", "categories": ["carpet"] },
{"id": "minecraft:mushroom_stew", "itemId": 282, "icon": "", "displayName": "Mushroom Stew", "shortName": "MushroomStew", "categories": ["food"] },
{"id": "minecraft:mycelium", "itemId": 110, "icon": "", "displayName": "Mycelium", "shortName": "Mycelium", "categories": ["dirt"] },
{"id": "minecraft:nether_gold_ore", "itemId": -288, "icon": "", "displayName": "Nether Gold Ore", "shortName": "NetherGoldOre", "categories": ["ore"] },
{"id": "minecraft:netherite_axe", "itemId": 643, "icon": "", "displayName": "Netherite Axe", "shortName": "NetheriteAxe", "categories": ["netheriteTools", "tools"] },
{"id": "minecraft:netherite_boots", "itemId": 649, "icon": "", "displayName": "Netherite Boots", "shortName": "NetheriteBoots", "categories": ["netheriteArmor", "armor"] },
{"id": "minecraft:netherite_chestplate", "itemId": 647, "icon": "", "displayName": "Netherite Chestplate", "shortName": "NetheriteChestplate", "categories": ["netheriteArmor", "armor"] },
{"id": "minecraft:netherite_helmet", "itemId": 646, "icon": "", "displayName": "Netherite Helmet", "shortName": "NetheriteHelmet", "categories": ["netheriteArmor", "armor"] },
{"id": "minecraft:netherite_hoe", "itemId": 644, "icon": "", "displayName": "Netherite Hoe", "shortName": "NetheriteHoe", "categories": ["netheriteTools", "tools"] },
{"id": "minecraft:netherite_ingot", "itemId": 645, "icon": "", "displayName": "Netherite Ingot", "shortName": "NetheriteIngot", "categories": ["metalIngots"] },
{"id": "minecraft:netherite_leggings", "itemId": 648, "icon": "", "displayName": "Netherite Leggings", "shortName": "NetheriteLeggings", "categories": ["netheriteArmor", "armor"] },
{"id": "minecraft:netherite_pickaxe", "itemId": 642, "icon": "", "displayName": "Netherite Pickaxe", "shortName": "NetheritePickaxe", "categories": ["netheriteTools", "tools"] },
{"id": "minecraft:netherite_shovel", "itemId": 641, "icon": "", "displayName": "Netherite Shovel", "shortName": "NetheriteShovel", "categories": ["netheriteTools", "tools"] },
{"id": "minecraft:netherite_sword", "itemId": 640, "icon": "", "displayName": "Netherite Sword", "shortName": "NetheriteSword", "categories": ["netheriteTools", "tools"] },
{"id": "minecraft:netherrack", "itemId": 87, "icon": "", "displayName": "Netherrack", "shortName": "Netherrack", "categories": ["stone"] },
{"id": "minecraft:oak_leaves", "itemId": 18, "icon": "", "displayName": "Oak Leaves", "shortName": "OakLeaves", "categories": ["leaves"] },
{"id": "minecraft:oak_log", "itemId": 17, "icon": "", "displayName": "Oak Log", "shortName": "OakLog", "categories": ["log"] },
{"id": "minecraft:oak_planks", "itemId": 5, "icon": "", "displayName": "Oak Planks", "shortName": "OakPlanks", "categories": ["plank"] },
{"id": "minecraft:oak_sapling", "itemId": 6, "icon": "", "displayName": "Oak Sapling", "shortName": "OakSapling", "categories": ["saplings"] },
{"id": "minecraft:orange_carpet", "itemId": -597, "icon": "", "displayName": "Orange Carpet", "shortName": "OrangeCarpet", "categories": ["carpet"] },
{"id": "minecraft:orange_wool", "itemId": -557, "icon": "", "displayName": "Orange Wool", "shortName": "OrangeWool", "categories": ["wool"] },
{"id": "minecraft:oxidized_copper_door", "itemId": -787, "icon": "", "displayName": "Oxidized Copper Door", "shortName": "OxidizedCopperDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:pale_moss_carpet", "itemId": -1010, "icon": "", "displayName": "Pale Moss Carpet", "shortName": "PaleMossCarpet", "categories": ["carpet"] },
{"id": "minecraft:pale_oak_door", "itemId": -990, "icon": "", "displayName": "Pale Oak Door", "shortName": "PaleOakDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:pale_oak_leaves", "itemId": -1007, "icon": "", "displayName": "Pale Oak Leaves", "shortName": "PaleOakLeaves", "categories": ["leaves"] },
{"id": "minecraft:pale_oak_log", "itemId": -995, "icon": "", "displayName": "Pale Oak Log", "shortName": "PaleOakLog", "categories": ["log"] },
{"id": "minecraft:pale_oak_planks", "itemId": -996, "icon": "", "displayName": "Pale Oak Planks", "shortName": "PaleOakPlanks", "categories": ["plank"] },
{"id": "minecraft:pale_oak_sapling", "itemId": -1006, "icon": "", "displayName": "Pale Oak Sapling", "shortName": "PaleOakSapling", "categories": ["saplings"] },
{"id": "minecraft:peony", "itemId": -867, "icon": "", "displayName": "Peony", "shortName": "Peony", "categories": ["flower"] },
{"id": "minecraft:pink_carpet", "itemId": -602, "icon": "", "displayName": "Pink Carpet", "shortName": "PinkCarpet", "categories": ["carpet"] },
{"id": "minecraft:pink_wool", "itemId": -566, "icon": "", "displayName": "Pink Wool", "shortName": "PinkWool", "categories": ["wool"] },
{"id": "minecraft:podzol", "itemId": 243, "icon": "", "displayName": "Podzol", "shortName": "Podzol", "categories": ["dirt"] },
{"id": "minecraft:poisonous_potato", "itemId": 304, "icon": "", "displayName": "Poisonous Potato", "shortName": "PoisonousPotato", "categories": ["food"] },
{"id": "minecraft:poppy", "itemId": 38, "icon": "", "displayName": "Poppy", "shortName": "Poppy", "categories": ["flower"] },
{"id": "minecraft:porkchop", "itemId": 284, "icon": "", "displayName": "Porkchop", "shortName": "Porkchop", "categories": ["food"] },
{"id": "minecraft:potato", "itemId": 302, "icon": "", "displayName": "Potato", "shortName": "Potato", "categories": ["food"] },
{"id": "minecraft:prismarine", "itemId": 168, "icon": "", "displayName": "Prismarine", "shortName": "Prismarine", "categories": ["stone"] },
{"id": "minecraft:pufferfish", "itemId": 289, "icon": "", "displayName": "Pufferfish", "shortName": "Pufferfish", "categories": ["food"] },
{"id": "minecraft:pumpkin_pie", "itemId": 306, "icon": "", "displayName": "Pumpkin Pie", "shortName": "PumpkinPie", "categories": ["food"] },
{"id": "minecraft:purple_carpet", "itemId": -606, "icon": "", "displayName": "Purple Carpet", "shortName": "PurpleCarpet", "categories": ["carpet"] },
{"id": "minecraft:purple_wool", "itemId": -564, "icon": "", "displayName": "Purple Wool", "shortName": "PurpleWool", "categories": ["wool"] },
{"id": "minecraft:quartz_ore", "itemId": 153, "icon": "", "displayName": "Quartz Ore", "shortName": "QuartzOre", "categories": ["ore"] },
{"id": "minecraft:rabbit", "itemId": 310, "icon": "", "displayName": "Rabbit", "shortName": "Rabbit", "categories": ["food"] },
{"id": "minecraft:rabbit_stew", "itemId": 312, "icon": "", "displayName": "Rabbit Stew", "shortName": "RabbitStew", "categories": ["food"] },
{"id": "minecraft:red_carpet", "itemId": -610, "icon": "", "displayName": "Red Carpet", "shortName": "RedCarpet", "categories": ["carpet"] },
{"id": "minecraft:red_sandstone", "itemId": 179, "icon": "", "displayName": "Red Sandstone", "shortName": "RedSandstone", "categories": ["stone"] },
{"id": "minecraft:red_tulip", "itemId": -833, "icon": "", "displayName": "Red Tulip", "shortName": "RedTulip", "categories": ["flower"] },
{"id": "minecraft:red_wool", "itemId": -556, "icon": "", "displayName": "Red Wool", "shortName": "RedWool", "categories": ["wool"] },
{"id": "minecraft:redstone_ore", "itemId": 73, "icon": "", "displayName": "Redstone Ore", "shortName": "RedstoneOre", "categories": ["ore"] },
{"id": "minecraft:rotten_flesh", "itemId": 299, "icon": "", "displayName": "Rotten Flesh", "shortName": "RottenFlesh", "categories": ["food"] },
{"id": "minecraft:salmon", "itemId": 287, "icon": "", "displayName": "Salmon", "shortName": "Salmon", "categories": ["food"] },
{"id": "minecraft:sand", "itemId": 12, "icon": "", "displayName": "Sand", "shortName": "Sand", "categories": ["dirt"] },
{"id": "minecraft:sandstone", "itemId": 24, "icon": "", "displayName": "Sandstone", "shortName": "Sandstone", "categories": ["stone"] },
{"id": "minecraft:smooth_stone", "itemId": -183, "icon": "", "displayName": "Smooth Stone", "shortName": "SmoothStone", "categories": ["stone"] },
{"id": "minecraft:spruce_door", "itemId": 586, "icon": "", "displayName": "Spruce Door", "shortName": "SpruceDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:spruce_door", "itemId": 193, "icon": "", "displayName": "Spruce Door", "shortName": "SpruceDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:spruce_leaves", "itemId": -800, "icon": "", "displayName": "Spruce Leaves", "shortName": "SpruceLeaves", "categories": ["leaves"] },
{"id": "minecraft:spruce_log", "itemId": -569, "icon": "", "displayName": "Spruce Log", "shortName": "SpruceLog", "categories": ["log"] },
{"id": "minecraft:spruce_planks", "itemId": -739, "icon": "", "displayName": "Spruce Planks", "shortName": "SprucePlanks", "categories": ["plank"] },
{"id": "minecraft:spruce_sapling", "itemId": -825, "icon": "", "displayName": "Spruce Sapling", "shortName": "SpruceSapling", "categories": ["saplings"] },
{"id": "minecraft:stone", "itemId": 1, "icon": "", "displayName": "Stone", "shortName": "Stone", "categories": ["stone"] },
{"id": "minecraft:stone_axe", "itemId": 339, "icon": "", "displayName": "Stone Axe", "shortName": "StoneAxe", "categories": ["stoneTools", "tools"] },
{"id": "minecraft:stone_hoe", "itemId": 355, "icon": "", "displayName": "Stone Hoe", "shortName": "StoneHoe", "categories": ["stoneTools", "tools"] },
{"id": "minecraft:stone_pickaxe", "itemId": 338, "icon": "", "displayName": "Stone Pickaxe", "shortName": "StonePickaxe", "categories": ["stoneTools", "tools"] },
{"id": "minecraft:stone_shovel", "itemId": 337, "icon": "", "displayName": "Stone Shovel", "shortName": "StoneShovel", "categories": ["stoneTools", "tools"] },
{"id": "minecraft:stone_sword", "itemId": 336, "icon": "", "displayName": "Stone Sword", "shortName": "StoneSword", "categories": ["stoneTools", "tools"] },
{"id": "minecraft:stripped_acacia_log", "itemId": -8, "icon": "", "displayName": "Stripped Acacia Log", "shortName": "StrippedAcaciaLog", "categories": ["log"] },
{"id": "minecraft:stripped_birch_log", "itemId": -6, "icon": "", "displayName": "Stripped Birch Log", "shortName": "StrippedBirchLog", "categories": ["log"] },
{"id": "minecraft:stripped_cherry_log", "itemId": -535, "icon": "", "displayName": "Stripped Cherry Log", "shortName": "StrippedCherryLog", "categories": ["log"] },
{"id": "minecraft:stripped_dark_oak_log", "itemId": -9, "icon": "", "displayName": "Stripped Dark Oak Log", "shortName": "StrippedDarkOakLog", "categories": ["log"] },
{"id": "minecraft:stripped_jungle_log", "itemId": -7, "icon": "", "displayName": "Stripped Jungle Log", "shortName": "StrippedJungleLog", "categories": ["log"] },
{"id": "minecraft:stripped_mangrove_log", "itemId": -485, "icon": "", "displayName": "Stripped Mangrove Log", "shortName": "StrippedMangroveLog", "categories": ["log"] },
{"id": "minecraft:stripped_oak_log", "itemId": -10, "icon": "", "displayName": "Stripped Oak Log", "shortName": "StrippedOakLog", "categories": ["log"] },
{"id": "minecraft:stripped_pale_oak_log", "itemId": -994, "icon": "", "displayName": "Stripped Pale Oak Log", "shortName": "StrippedPaleOakLog", "categories": ["log"] },
{"id": "minecraft:stripped_spruce_log", "itemId": -5, "icon": "", "displayName": "Stripped Spruce Log", "shortName": "StrippedSpruceLog", "categories": ["log"] },
{"id": "minecraft:sunflower", "itemId": 175, "icon": "", "displayName": "Sunflower", "shortName": "Sunflower", "categories": ["flower"] },
{"id": "minecraft:sweet_berries", "itemId": 309, "icon": "", "displayName": "Sweet Berries", "shortName": "SweetBerries", "categories": ["food"] },
{"id": "minecraft:torchflower", "itemId": -568, "icon": "", "displayName": "Torchflower", "shortName": "Torchflower", "categories": ["flower"] },
{"id": "minecraft:tuff", "itemId": -333, "icon": "", "displayName": "Tuff", "shortName": "Tuff", "categories": ["stone"] },
{"id": "minecraft:warped_door", "itemId": 654, "icon": "", "displayName": "Warped Door", "shortName": "WarpedDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:warped_planks", "itemId": -243, "icon": "", "displayName": "Warped Planks", "shortName": "WarpedPlanks", "categories": ["plank"] },
{"id": "minecraft:waterlily", "itemId": 111, "icon": "", "displayName": "Waterlily", "shortName": "Waterlily", "categories": ["flower"] },
{"id": "minecraft:waxed_copper_door", "itemId": -788, "icon": "", "displayName": "Waxed Copper Door", "shortName": "WaxedCopperDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:waxed_exposed_copper_door", "itemId": -789, "icon": "", "displayName": "Waxed Exposed Copper Door", "shortName": "WaxedExposedCopperDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:waxed_oxidized_copper_door", "itemId": -791, "icon": "", "displayName": "Waxed Oxidized Copper Door", "shortName": "WaxedOxidizedCopperDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:waxed_weathered_copper_door", "itemId": -790, "icon": "", "displayName": "Waxed Weathered Copper Door", "shortName": "WaxedWeatheredCopperDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:weathered_copper_door", "itemId": -786, "icon": "", "displayName": "Weathered Copper Door", "shortName": "WeatheredCopperDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:wheat", "itemId": 359, "icon": "", "displayName": "Wheat", "shortName": "Wheat", "categories": ["crops"] },
{"id": "minecraft:white_carpet", "itemId": 171, "icon": "", "displayName": "White Carpet", "shortName": "WhiteCarpet", "categories": ["carpet"] },
{"id": "minecraft:white_wool", "itemId": 35, "icon": "", "displayName": "White Wool", "shortName": "WhiteWool", "categories": ["wool"] },
{"id": "minecraft:wither_rose", "itemId": -216, "icon": "", "displayName": "Wither Rose", "shortName": "WitherRose", "categories": ["flower"] },
{"id": "minecraft:wooden_axe", "itemId": 335, "icon": "", "displayName": "Wooden Axe", "shortName": "WoodenAxe", "categories": ["woodenTools", "tools"] },
{"id": "minecraft:wooden_door", "itemId": 384, "icon": "", "displayName": "Wooden Door", "shortName": "WoodenDoor", "categories": ["furniture", "door"] },
{"id": "minecraft:wooden_hoe", "itemId": 354, "icon": "", "displayName": "Wooden Hoe", "shortName": "WoodenHoe", "categories": ["woodenTools", "tools"] },
{"id": "minecraft:wooden_pickaxe", "itemId": 334, "icon": "", "displayName": "Wooden Pickaxe", "shortName": "WoodenPickaxe", "categories": ["woodenTools", "tools"] },
{"id": "minecraft:wooden_shovel", "itemId": 333, "icon": "", "displayName": "Wooden Shovel", "shortName": "WoodenShovel", "categories": ["woodenTools", "tools"] },
{"id": "minecraft:wooden_sword", "itemId": 332, "icon": "", "displayName": "Wooden Sword", "shortName": "WoodenSword", "categories": ["woodenTools", "tools"] },
{"id": "minecraft:yellow_carpet", "itemId": -600, "icon": "", "displayName": "Yellow Carpet", "shortName": "YellowCarpet", "categories": ["carpet"] },
{"id": "minecraft:yellow_wool", "itemId": -558, "icon": "", "displayName": "Yellow Wool", "shortName": "YellowWool", "categories": ["wool"] }
];

const entityDatabase = [
    {"id": "minecraft:zombie", "itemId": 0, "icon": "", "displayName": "Zombie", "shortName": "zombie", "categories": ["hostileMobs"] },
    {"id": "minecraft:cow", "itemId": 0, "icon": "", "displayName": "Cow", "shortName": "cow", "categories": ["passiveMobs"] }
];


export const itemsData = itemDatabase;
export const entitiesData = entityDatabase;
